# -*- coding: utf-8 -*-
"""Preprocessing-Brixia-Images.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M0zt2g1PFoCrsJsGCQKpuTB59qyeYsJ1
"""

#pip install opencv-python

#pip install matplotlib numpy

# Commented out IPython magic to ensure Python compatibility.
import os
import cv2
from matplotlib import pyplot as plt
# %matplotlib inline


# Read images from folder
def load_images_from_folder(folder):

    images = dict()
    for filename in os.listdir(folder):
        img = cv2.imread(os.path.join(folder,filename))
        if img is not None:
            images[filename] = img
    return images


# Preprocess images
def preprocessing(images):

  enhanced_images = dict()
  icount = 0
  # for image in images:
  for fname, image in images.items():
    try:
      icount += 1
      print(f"Preprocessing Image#: {icount}, {fname}")

      # Remove Noise: Bilateral Filter
      noise_removed = cv2.bilateralFilter(image, 5, 75, 75)
     

      # Increase Contrast: Contrast Limited Adaptive Histogram Equalization
      noise_removed_bw = cv2.cvtColor(noise_removed, cv2.COLOR_BGR2GRAY)

      clahe = cv2.createCLAHE(clipLimit = 2) 
      enhanced_img = clahe.apply(noise_removed_bw) 


      enhanced_images[fname] = enhanced_img

    except Exception:
      print(f"\tSkipping Image# {fname}")
      enhanced_images[fname] = None

  return enhanced_images

# Save images to folder
def save_images_to_folder(images, path):
  icount = 0
  for fname, img in images.items():
    icount += 1
    if img is not None:
      opath = os.path.join(path , f'{fname}')
      cv2.imwrite(opath, img)

if __name__ == "__main__":

  # Load images
  # Folder path
  folder="/content/drive/MyDrive/Brixia-306/Lungs_cropped_brixia_306"
  images = load_images_from_folder(folder)
  print("Original images",len(images))

# Call preprocessing
enhanced_images = preprocessing(images)
print("Enhanced images",len(enhanced_images))

# Save preprocessed images in folder
path = "/content/drive/MyDrive/preprocess_final_check"
save_images_to_folder(enhanced_images, path)